name: shoppy_flutter
description: This is a Shopping app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 # Default icons asset for Cupertino widgets based on Apple styled icons
  # Provides internationalization and localization facilities, including message translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.17.0
  # RFC4122 (v1, v4, v5) UUID Generator and Parser for all Dart platforms (Web, VM, Flutter)
  uuid: ^3.0.4
  # Currency Text Input Formatter for Flutter. Use it easy and simple for your flutter app.
  currency_text_input_formatter: ^2.0.1
  # A Flutter widget to display a date time form field to show a date or clock dialog.
  date_time_picker: "^2.0.0"
  # RFlutter Alert is super customizable and easy-to-use alert / popup dialogs for Flutter. You may create reusable alert styles or add buttons as much as you want with ease.
  rflutter_alert: ^2.0.2
  # A library for generating fake data. faker is heavily inspired by the Python package faker and, the Ruby package ffaker.
  faker: ^2.0.0
  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^5.0.0
  # Flutter Color manipulation and conversion, ported from JS tinycolor2
  tinycolor: ^1.0.3
  # The Font Awesome Icon pack available as Flutter Icons. Provides 1500 additional icons to use in your apps.
  font_awesome_flutter: ^9.1.0
  # A Flutter plugin to play multiple simultaneously audio files, works for Android, iOS, macOS and web.
  audioplayers: ^0.19.0
  # Custom_Empty widget is flutter custom widget which is designed to notify user about some event.
  empty_widget: ^0.0.5
  # A splashscreen package created as intro for any flutter application easily with a lot of customization
  splashscreen: ^1.3.5
  # A Flutter plugin for reading device's native orientation, either from UI orientation or from sensors
  native_device_orientation: ^1.0.0
  # Flutter plugin for SQLite, a self-contained, high-reliability, embedded, SQL database engine.
  sqflite: ^2.0.0+3
  # A custom switch widget that can have a custom height and width, borders, border radius, colors, toggle size, custom text and icons inside the toggle.
  flutter_switch: ^0.3.1
  # Better conversion of ENUMs to string. Dart has annoying EnumName.ValueName syntax when calling enum.toString, this package fixes that.
  enum_to_string: ^2.0.1
  # A library to convert Dart values into human-friendly representations.
  humanizer: ^0.0.2
  # RouteObserveMixin provides easy access to didPush/didPop/didPushNext/didPopNext.
  route_observer_mixin: ^1.5.0+1
  # Filter_list Package is designed to make single/multiple item selection from a list of string/object. Allows to search/filter on the basis of single/multiple selection from a provided dynamic list.
  filter_list: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/

  fonts:
    - family: Luminari
      fonts:
        - asset: assets/fonts/Luminari/Luminari-Regular.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Luminari/Luminari-Regular.woff
          style: normal
          weight: 500
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
          style: normal
          weight: 500
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed/RobotoCondensed-Regular.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/RobotoCondensed/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed/RobotoCondensed-Italic.ttf
          style: italic
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons/AppIcons.ttf